CREATE TABLE tickets (
  id SERIAL PRIMARY KEY,
  game_id INTEGER REFERENCES games(id) ON DELETE CASCADE NOT NULL,
  section TEXT NOT NULL,
  seat_row TEXT NOT NULL,
  seats INT [] NOT NULL,
  quantity INT NOT NULL,
  singles_allowed BOOLEAN DEFAULT FALSE NOT NULL,
  available BOOLEAN DEFAULT TRUE NOT NULL ,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);